job_build_dotnet:
    stage: build
    image: microsoft/dotnet:latest
    script:
        - dotnet restore
        - dotnet publish SitemapWeb -c release
job_deploy:
    stage: deploy
    image: microsoft/dotnet:latest
    script: 
        - mkdir /home/scott/sites/sitemapweb
        - cp * -R /home/scott/sites/sitemapweb
    dependencies:
        - job_build_dotnet