stages:
    - build
    - deploy
job:
    stage: build
    script:
        - echo "Building"
        - dotnet restore
        - dotnet publish SitemapWeb -c release
        - echo "Finished building"
job:
    stage: deploy
    script: 
        - echo "Deploying"
        - mkdir -p /home/gitlab-runner/sites/sitemapweb
        - cp * -R /home/scott/sites/sitemapweb
        - echo "Finished deploying"
        - pwd
    dependencies:
        - job_build_dotnet