stages:
    - build
job:
    stage: build
    script:
        - echo "Building"
        - mkdir -p /home/gitlab-runner/sites/sitemapweb
        - dotnet restore
        - dotnet publish SitemapWeb -c release -o /home/gitlab-runner/sites/sitemapweb
        - echo "Finished build & release"